sudo: required
language: node_js
node_js:
  - "14"

services:
  - docker

before_install:
  - docker build -t ppreis/docker-mini-react-project -f Dockerfile.dev .

script:
  - 
  - docker run -e CI=true ppreis/docker-mini-react-project npm run test